dubbo:
  application:
    name: mall_user_provider
  registry:
    address: zookeeper://192.168.32.188:2181
  consumer:
    check: false
  protocol:
    port: -1

spring:
  datasource:
    url: jdbc:mysql:///mall1909?serverTimezone=GMT%2B8
    username: root
    password: mz666672
    driver-class-name: com.mysql.cj.jdbc.Driver
