server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql:///mall1909?serverTimezone=GMT%2B8
    username: root
    password: mz666672
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 192.168.32.188
    port: 5672
    #默认是guest
    username: guest
    password: guest
    #虚拟主机地址 /
    virtual-host: /

  redis:
    host: 192.168.32.188

dubbo:
  application:
    name: mall_goods
  protocol:
    port: -1
  registry:
    address: zookeeper://192.168.32.188:2181
  consumer:
    check: false




